remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [AKUVEG]
description: ["Project to investigate traffic noise attenuation by vegetation"]

logo: "https://github.com/VUKOZ-OEL/AKUVEG/blob/main/docs/assets/images/logo2.png?raw=true"

github:
  zip_url: http://example.com/download.zip
  another_url: http://example.com/download.zip
