
title: ACUVEG
description: Determination and optimization of vegetation belts of natural woody composition serving to traffic noise attenuation.
show_downloads: true
darkmode: false

hide_first_title: true # Useful if README.md is used on both github and pages

include: ['_pages']

colors:
  header: "#000"
  gradient_left: "#a3a367"
  gradient_right: "#f57c00"
  android_theme: "#000" # this default to gradient_color
  link: "#000000" # this default to gradient_color #1e6bb8
  section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: https://github.com/VUKOZ-OEL/AKUVEG/blob/main/docs/project_details.html
      zip_title: Project details
      zip_hide: false
      tar_url: https://github.com/VUKOZ-OEL/AKUVEG/blob/main/DATABASE/readme.html
      tar_title: Noise attenuation database
      tar_hide: false
      github_hide: true # hides "View on Github"