remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [AKUVEG]
description: ["A project to investigate traffic noise attenuation by vegetation"]

logo: "https://github.com/VUKOZ-OEL/AKUVEG/blob/main/docs/assets/images/logo.png?raw=true"


zip_download: "https://example.com/path/to/your/file.zip"
other_link: "https://example.com/your-page"
