remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Traffic noise attenuation]
description: ["test \n test \n test 3"]

logo: "https://github.com/VUKOZ-OEL/AKUVEG/blob/main/docs/assets/images/logo.webp?raw=true"



