remote_theme: "mmistakes/minimal-mistakes"
# remote_theme: tuur29/pages-themes-cayman 
title: ACUVEG Project
#description: Determination and optimization of vegetation belts of natural woody composition serving to traffic noise attenuation.



